# Generated by Django 3.2 on 2021-08-21 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partner',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.country'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='agr_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.agreementtype'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.partner'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.representative'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='research_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.researchdomain'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.status'),
        ),
    ]
