# Generated by Django 3.2 on 2021-08-20 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreementtype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agreementtype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='country',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='country',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='engineeringschool',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='engineeringschool',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='researchdomain',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='researchdomain',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='agreement',
            name='id_agr_type',
            field=models.ForeignKey(db_column='id_agr_type', on_delete=django.db.models.deletion.DO_NOTHING, to='api.agreementtype'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='id_research_domain',
            field=models.ForeignKey(db_column='id_research_domain', on_delete=django.db.models.deletion.DO_NOTHING, to='api.researchdomain'),
        ),
    ]
