# Generated by Django 3.2 on 2021-12-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='engineeringschool',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['second_name']},
        ),
        migrations.AlterModelOptions(
            name='representative',
            options={'ordering': ['second_name']},
        ),
        migrations.AlterModelOptions(
            name='researchdomain',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name']},
        ),
    ]
