# Generated by Django 3.2 on 2021-08-21 08:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210820_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='news_url',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='third_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='representative',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='representative',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='representative',
            name='third_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
