# Generated by Django 3.2 on 2021-08-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
