# Generated by Django 3.2 on 2021-12-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211202_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineeringschool',
            name='full_name',
            field=models.CharField(default='default full name', max_length=200),
            preserve_default=False,
        ),
    ]
