# Generated by Django 3.2 on 2021-12-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'ordering': ['name']},
        ),
    ]
