# Generated by Django 3.2 on 2021-08-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210820_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='updated_at',
        ),
    ]
